target:
	g++ -Wall -g -o randomGenerator randomGenerator.cpp
	g++ -Wall -g -o emptyGenerator emptyGenerator.cpp
	g++ -Wall -g -o point2matrix point2matrix.cpp

clean:
	/bin/rm -rf randomGenerator
	/bin/rm -rf point2matrix
